export const TODO_CONST_ACTIONS = {
  CREATE_TODO_ACTION: "CREATE_TODO_ACTION",
  SEND_EACH_TODO_ID_ACTION: "SEND_EACH_TODO_ID_ACTION",
  SEND_EACH_TODO_ALL_ACTION: "SEND_EACH_TODO_ALL_ACTION",
  UPDATE_TODO_ACTION: "UPDATE_TODO_ACTION",
  DELETE_TODO_ACTION: "DELETE_TODO_ACTION",
  MARK_AS_DONE_ACTION: "MARK_AS_DONE_ACTION",
};
